# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFh213_jeU8TqIZBwxX2fvoG-FzZw9Xt
"""

import numpy as np
import random

ventricle_index=np.nonzero(ventricle)
skull_index=np.nonzero(skull)
obstruct_index=np.nonzero(obstruct)
print(ventricle_index)
print(skull_index)
print(obstruct_index)

ventricle_index = np.array(ventricle_index)
ventricle_index=ventricle_index.T

idx = np.random.randint(55455, size=1000)

ventricle_random_points=ventricle_index[idx,:]
print('ventricle_random_points','\n',ventricle_random_points)

skull_index = np.array(skull_index)
skull_index=skull_index.T

skull_random_points=skull_index[idx,:]
print('skull_random_points','\n',skull_random_points)

obstruct_index = np.array(obstruct_index)
obstruct_index=obstruct_index.T

obstruct_random_points=obstruct_index[idx,:]
print('pbstruct_random_points','\n',obstruct_random_points)

segment_ventricle=[]
skull=[]
obstruct=[]

from sympy import Point3D, Matrix
from sympy.abc import x
for i in range(1000):
  for j in range(1000):
     p1, p2 = Point3D(ventricle_random_points[i]), Point3D(skull_random_points[j])
     for k in range(1000):
      p3= Point3D(obstruct_random_points[k])
      if Point3D.are_collinear(p1, p2)==True and Point3D.are_collinear(p1, p2, p3)==False:
        segment_ventricle.append(p1)
        skull.append(p2)
        obstruct.append(p3)



